[connections.snowflake]
account = "OZNWZHA-CYB61847"
user = "JMDEMERATH"
password = "Snowflake*Learning26"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
